Added some stuff for the ping event
oatmealraisin/openshift-github-listener pull request #1
Opened 2018-04-09 21:07 UTC by oatmealraisin

Woo time to figure out what happens with a PR

2018-04-09 21:09 UTC, oatmealraisin commented
Comment?

2018-04-09 21:09 UTC, oatmealraisin commented
Request a review!

2018-04-09 21:47 UTC, finiteautomatom requested changes

2018-04-09 21:47 UTC, finiteautomatom commented on listener.go
> +	secretKey = []byte("killme")
What is thing? Hahaha

2018-05-08 14:41 UTC, oatmealraisin commented
Comment

2018-05-08 15:00 UTC, merged